
Wooden cubes fascinate children and adults alike – even before doing any mathematics with them. This enthusiasm is worth taking advantage of! Especially in geometry lessons, but also beyond that, there are numerous occasions to use cubes to approach mathematical topics.

Of course this works with actual wooden cubes, pretty well actually. Should experiences like that really be replaced by an app? No! But those **experiences** can be wonderfully **expanded** upon. Here, a few special features come into play that only **digital tools** can provide. These lead to further spatial cognition or more opportunities to support and challenge your students.

The **Cubeling app** introduced here is available free of charge for iOS and macOS devices (i.e. iPads, Macs, and, to a limited extent, iPhones) under https://apps.apple.com/en/app/cubeling/id1027746349.

## About this "book" {-}

The first chapter of this document will provide instructions as to **[how to use](#how-to-use)** the app itself.

The following chapters will include possible applications for teaching mathematics -- on one hand with a focus on **[spatial reasoning](#Shadow)**, on the other on **[coding](#Coding)** in connection with the building of cube structures.  

The contents of this book are not set in stone. Over time -  things will be changed. We will also gladly take up any suggestions in order to share more ideas on how to use the Cubeling app in the classroom. 

This book refers to **Version 7.1 of the Cubeling app**, however, many functions are also available with earlier versions. The book, especially chapter \@ref(Coding), builds on a previous, two-part guide (view @Etzold:2018Praxis1 and @Etzold:2018Praxis2).

The book is written in a way that makes it easy to read cover to cover, but it is also intended to function as a quick reference work.

::: {.task}
Tasks for students can be found in the coloured text boxes. 
:::
    
::: {.hint}
Gray text boxes provide further hints that can, for example, be used in class discussions.
:::


> In addition, didactic comments on individual topics are scattered throughout the book. Tips on which materials are suitable for certain teaching situations and which settings are needed in the Cubeling app are also provided.


**Additional material**, like the compilation of all tasks and worksheets referred to in the individual sections, can be found at the [end of the book](#Material).

## Licenses and versions of this book {-}

This material is an **open educational resource** and is licensed under the Creative-Commons attribution ShareAlike 4.0 (**CC BY-SA 4.0**). To view a copy of this license, visit [https://creativecommons.org/licenses/by-sa/4.0/deed.en](https://creativecommons.org/licenses/by-sa/4.0/deed.en){target="_blank"}.

It is both possible and desired to **freely use, modify, and develop the material** and publish it accordingly. If appropriate, changes or additions, such as translated contents, can also be included in the book itself -- simply [contact me](mailto:heiko.etzold@uni-potsdam.de) for that.

The **raw data** of the book is available at [https://github.com/heiko-etzold/cubeling-material](https://github.com/heiko-etzold/cubeling-material){target="_blank"}. There, via a GIT-repository, earlier versions and the changes can be tracked.
An overview of all versions of the book can be found at https://heiko-etzold.github.io/cubeling-material.
